# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('ease', models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], default=1)),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Now'), (2, 'Urgent'), (3, 'Semi Urgent'), (4, 'Non Urgent')], default=4)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='userprofile.Profile')),
            ],
        ),
    ]
