# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(choices=[(4, 'Non Urgent'), (3, 'Urgent'), (2, 'Semi-Urgent'), (1, 'Now')], default=4),
        ),
    ]
