"""."""

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:12
from __future__ import unicode_literals
import django.core.validators
import django
from django.db import migrations, models
import re

def load_medications_from_fixture(apps, schema_editor):
    """."""
    from django.core.management import call_command
    call_command("loaddata", "medication")


class Migration(migrations.Migration):
    """."""

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='post_peak_easy_end',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='post_peak_easy_start',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='post_peak_medium_end',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='post_peak_medium_start',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.RunPython(load_medications_from_fixture)
    ]
