"""."""

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:12
from __future__ import unicode_literals

from django.db import migrations


def load_medications_from_fixture(apps, schema_editor):
    """."""
    from django.core.management import call_command
    call_command("loaddata", "medication")


class Migration(migrations.Migration):
    """."""

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_medications_from_fixture),
    ]
