# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_period_start', models.TimeField(default=datetime.time(8, 0))),
                ('active_period_end', models.TimeField(default=datetime.time(22, 0))),
                ('peak_period', models.CharField(choices=[('early_bird', 'Early Bird'), ('morning', 'Morning'), ('midday', 'Midday'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night_owl', 'Night Owl')], default='Morning', max_length=15)),
                ('dose_time', models.TimeField(default=datetime.time(8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
