# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_credentialsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='peak_period',
            field=models.CharField(choices=[('Early Bird', 'Early Bird'), ('morning', 'Morning'), ('midday', 'Midday'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('Night Owl', 'Night Owl')], default='Morning', max_length=15),
        ),
    ]
